export const Genres = [
  "Ação",
  "Aventura",
  "Animação",
  "Biografia",
  "Comédia",
  "Comédia Romântica",
  "Crime",
  "Documentário",
  "Drama",
  "Família",
  "Fantasia",
  "Faroeste",
  "Ficção Científica",
  "Guerra",
  "Histórico",
  "Mistério",
  "Musical",
  "Romance",
  "Suspense",
  "Terror",
  "Thriller Psicológico",
  "Esportes",
  "Cinema Independente",
  "Filme Noir",
  "Épico/Heroico",
  "Super-heróis",
  "Policial",
  "Cult",
  "Experimental",
  "Teatro",
  "Filme de Época",
  "Filme LGBTQ+",
  "Anime",
  "Live-action",
  "Antologia",
  "Mockumentary",
  "Filme de Zumbi",
  "Filme de Vampiro",
  "Cyberpunk",
  "Steampunk"
];
